version: '3.1'
services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
      - ./app/node_modules:/api/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true